<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>Umbraco.Community.Automate.Extensions</AssemblyName>
		<RootNamespace>Umbraco.Community.Automate.Extensions</RootNamespace>
		<PackageId>Umbraco.Community.Automate.Extensions</PackageId>
	</PropertyGroup>

	<PropertyGroup>
		<Version>17.0.0-beta3</Version>
		<PackageId>Umbraco.Community.Automate.Extensions</PackageId>
		<Product>Umbraco.Community.Automate.Extensions</Product>
		<Title>Umbraco.Community.Automate.Extensions</Title>
		<Description>Extension package for Umbraco.Automate</Description>
		<Authors>Erik-Jan Westendorp</Authors>
		<PackageTags>umbraco plugin package published content urls</PackageTags>
		<PackageIcon>heading-icon-128.png</PackageIcon>
		<PackageProjectUrl>https://github.com/erikjanwestendorp/Umbraco.Community.Automate</PackageProjectUrl>
		<RepositoryUrl>https://github.com/erikjanwestendorp/Umbraco.Community.Automate</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\assets\community-automate-128.png" Pack="true" PackagePath="\" />
		<None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
	</ItemGroup>
	
	<ItemGroup>
		<!--Umbraco CMS Packages-->
		<PackageReference Include="Umbraco.Cms.Core" />
	</ItemGroup>

	<ItemGroup>
		<!--Umbraco Products Packages-->
		<PackageReference Include="Umbraco.Automate.Core" />
	</ItemGroup>

</Project>
